[package]
name = "roller-lsp"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
roller-parser = { path = "../roller-parser" }
roller-transpiler = { path = "../roller-transpiler" }
serde_json.workspace = true

[lints]
workspace = true
