[package]
name = "roller-transpiler"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
roller-parser = { path = "../roller-parser" }
roller-diagnostics = { path = "../roller-diagnostics" }
thiserror.workspace = true

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
